### ISSUE TITLE
Receiving 500 HTMLElement is not defined error

### ISSUE THREAD

**Issue by andrebell** [graphieros/vue-data-ui-nuxt#1] opened 2024-02-23 12:46 UTC
I've cloned the repository and tried to run it with `npm run dev` and get the following error:

```
[Vue Router warn]: uncaught error during route navigation:
ReferenceError: HTMLElement is not defined
    at file:///C:/Users/<some path>/GitHub/vue-data-ui-nuxt/node_modules/vue-data-ui/dist/index-884155c8.js:17960:13
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async ViteNodeRunner.interopedImport (file:///C:/Users/<some path>/GitHub/vue-data-ui-nuxt/node_modules/vite-node/dist/client.mjs:383:28)
    at async ViteNodeRunner.directRequest (file:///C:/Users/<some path>/GitHub/vue-data-ui-nuxt/node_modules/vite-node/dist/client.mjs:253:24)    at async ViteNodeRunner.cachedRequest (file:///C:/Users/<some path>/GitHub/vue-data-ui-nuxt/node_modules/vite-node/dist/client.mjs:189:14)    at async ViteNodeRunner.dependencyRequest (file:///C:/Users/<some path>/GitHub/vue-data-ui-nuxt/node_modules/vite-node/dist/client.mjs:233:12)
    at async C:\Users\<some path>\GitHub\vue-data-ui-nuxt\pages\index.vue:5:31
    at async ViteNodeRunner.runModule (file:///C:/Users/<some path>/GitHub/vue-data-ui-nuxt/node_modules/vite-node/dist/client.mjs:362:5)     
    at async ViteNodeRunner.directRequest (file:///C:/Users/<some path>/GitHub/vue-data-ui-nuxt/node_modules/vite-node/dist/client.mjs:346:5) 
```

**Comment by graphieros** [comment] 2024-02-23 12:57
Hi, I pushed a fix, this was caused by a missing import.
Thanks for eaching out:)

**Closed as completed by graphieros** 2024-02-23 12:57 UTC
